#!/bin/sh
# Refuse to commit files with the string NOCOMMIT, debugger, or merge markers present.
#

# Exit code
ERROR=0
unitTestFlag=0
coverageTestFlag=0
metricsFlag=0
pmdFlag=0

echo "----------Running Unit Test----------"
node unit-test.js
ret=$?
if [ $ret -ne 0 ]; then
   unitTestFlag=1
   ERROR=1
fi
echo "----------Unit Test Finished----------"

# Coverage check
node main.js mystery.js >/dev/null
node_modules/.bin/istanbul cover test.js > test.txt 2>/dev/null
cat test.txt
node cover.js
ret=$?
if [ $ret -ne 0 ]; then
	coverageTestFlag=1
	ERROR=1
	echo "Did not meet coverage requirements!"
fi

echo ""

echo "----------Running Basic Metrics----------"
node metrics.js mystery.js
ret=$?
if [ $ret -ne 0 ]; then
   metricsFlag=1
   ERROR=1
else
   echo "OK"
fi
echo "----------Basic Metrics Finished----------"

echo ""

echo "----------PMD Report----------------------"
sh run_pmd.sh
if [ -f "PMD_Report.txt" ]
then
    cat PMD_Report.txt
    error_num=`wc -l PMD_Report.txt`
    SUBSTRING=$(echo $error_num| cut -d ' ' -f 1)
    #echo $SUBSTRING
    if test $SUBSTRING -gt 6
    then
       pmdFlag=1 
       ERROR=1
    fi
fi
echo "----------End of PMD Report----------------"

echo ""

if [ $ERROR -eq 1 ]; then
	echo "Pre-commit check failed! "
	if [ $unitTestFlag -eq 1 ]; then
		echo "Unit Test Failed!"
   	fi
   	if [ $coverageTestFlag -eq 1 ]; then
		echo "Coverage Test Failed!"
   	fi
   	if [ $metricsFlag -eq 1 ]; then
		echo "Metrics Test Failed!"
   	fi
   	if [ $pmdFlag -eq 1 ]; then
		echo "PMD Test Failed!"
   	fi
else
   echo "PASS"
fi

exit $ERROR
